Improve README and fix compatibility with latest version
dbjohnson/starlink-monitor pull request #6
Opened 2021-09-23 10:05 UTC by xsellier

Hey,

Thank yo ufor that wonderful application.
I'm also a Starlink user and I wanted to install starlink-monitor on a abare-metal reaspberry-i, so I added instructions to the README.md file to do it.

I noticed there was a compatibility issue with the latest firmware, so I tweaked the `starlink.py` to make it work.

Hope you'll like the changes

2021-09-23 11:23 UTC, dbjohnson requested changes
Hey @xsellier - thanks so much!  `starlink-monitor`'s first collaborator PR 🎉 !!

I appreciate adding the instructions for how to deploy on pi sans docker.  I had one question re: the threading change (just curious why) and two minor blockers:

1) the default HTTP port should stay at 80 - in the usual docker config, this is only exposed in container, and remapped to 3000 outside.  I'm fine with changing it to something other than 80 to support this bare install case, but then the README examples would need to be updated to match
2) All the white space changes need to be reverted.  I'm not super pedantic about this stuff, but I like to follow PEP8 ([4 space tabs](https://www.python.org/dev/peps/pep-0008/#indentation)).  More generally, most of these files have no functional change. 
 Probably just an auto-formatting issue, hopefully easy to back out :)

Thanks again for the PR - will be glad to merge if you are up for correcting those two issues!

2021-09-23 11:23 UTC, dbjohnson commented on Dockerfile
> +ENV SERVER_HTTP_PORT=3000
to match current default, this should be port 80; 3000 is what the container exposes

2021-09-23 11:23 UTC, dbjohnson commented on Dockerfile.arm32
> +ENV SERVER_HTTP_PORT=3000
to match current default, this should be port 80; 3000 is what the container exposes

2021-09-23 11:23 UTC, dbjohnson commented on README.md
> +## Deploy on bare-metal Raspberry pi
```suggestion
## Deploy on bare-metal Raspberry pi (without using Docker)
```

2021-09-23 11:23 UTC, dbjohnson commented on README.md
> +| `SERVER_HTTP_PORT`              | starlink monitoring server port          | 1337               |
```suggestion
| `SERVER_HTTP_PORT`              | starlink monitoring server port          | 80               |
```

2021-09-23 11:23 UTC, dbjohnson commented on app/app.py
> +socketio = SocketIO(app)
Can you describe why this change is necessary?

2021-09-23 16:46 UTC, dbjohnson commented on README.md
> +```bash
👍

2021-09-24 10:45 UTC, xsellier commented
Thank you for the review!

2021-09-24 14:29 UTC, dbjohnson requested changes
Thanks for updating the port!  Please see other comments from the initial review, particular the whitespace issue.

2021-09-24 14:29 UTC, dbjohnson commented on Dockerfile
> +ENV SERVER_HTTP_PORT=80
👍

2021-09-24 15:04 UTC, closed without merging

2021-09-24 15:04 UTC, xsellier commented
It's ok, I'm not gonna change the whitespaces, soryr for bothering

2021-09-24 15:09 UTC, dbjohnson commented
It's no bother - I sincerely appreciate the interest and offer for help!  

But, PRs shouldn't include reformatting to match individual stylistic preferences / dev setups.  It makes the functional changes hard to differentiate.